# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreterioGara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[(None, ''), ('L', 'Lavori'), ('S', 'Servizi'), ('F', 'Forniture')], max_length=1)),
                ('soglia', models.CharField(choices=[(None, ''), ('M', 'minore di 150.000'), ('C', 'compresi tra 150.000 e 1.000.000'), ('S', 'superiori a 1.000.000')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('password_confirm', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[(None, ''), ('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=30)),
                ('receive_news', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=1)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compilaGare.Shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Soggetto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(max_length=30)),
                ('cognome', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=30)),
                ('indirizzo', models.CharField(max_length=50)),
                ('citta', models.CharField(max_length=20)),
                ('data_di_nascita', models.DateField(blank=True, null=True)),
                ('sesso', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
            ],
        ),
    ]
