# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compilaGare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creteriogara',
            name='procedura',
            field=models.CharField(choices=[(None, ''), ('A', 'Procedura Aperta'), ('R', 'Procedura ristretta'), ('N', 'Procedura negoziata')], default=datetime.datetime(2016, 6, 8, 17, 25, 13, 325000, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
    ]
