# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 17:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compilaGare', '0002_creteriogara_procedura'),
    ]

    operations = [
        migrations.AddField(
            model_name='creteriogara',
            name='criterio_aggiudicazione',
            field=models.CharField(choices=[(None, ''), ('B', 'Prezzo pi\xf9 basso'), ('V', 'offerta economicamente pi\xf9 vantaggiosa')], default=datetime.datetime(2016, 6, 8, 17, 52, 7, 33000, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creteriogara',
            name='oggetto_contratto',
            field=models.CharField(choices=[(None, ''), ('S', 'Sola esecuzione'), ('R', 'Progettazione esecutiva ed esecuzione')], default=datetime.datetime(2016, 6, 8, 17, 52, 12, 751000, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creteriogara',
            name='pagamento_corrispettivo',
            field=models.CharField(choices=[(None, ''), ('C', 'Corpo'), ('M', 'Misura'), ('T', 'Corpo e misura')], default=datetime.datetime(2016, 6, 8, 17, 52, 22, 418000, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creteriogara',
            name='progetto_base_gara',
            field=models.CharField(choices=[(None, ''), ('E', 'Progetto esecutivo'), ('D', 'Progetto definitivo'), ('T', 'Pogettazione esecutiva ed esecuzione')], default=datetime.datetime(2016, 6, 8, 17, 52, 30, 309000, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
    ]
