# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-09 06:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compilaGare', '0004_auto_20160609_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='creteriogara',
            name='username',
            field=models.CharField(default=datetime.datetime(2016, 6, 9, 6, 16, 48, 778000, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
