# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-15 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compilaGare', '0005_creteriogara_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreterioGara',
            new_name='Gara',
        ),
    ]
