# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compilaGare', '0007_remove_gara_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soggetto',
            name='sesso',
            field=models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1),
        ),
    ]
